
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-watcher
  namespace: $WATCH_NAMESPACE

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pg-watcher-role
  namespace: $WATCH_NAMESPACE
rules:
- apiGroups:
  - '*'
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pg-watcher-role-binding
  namespace: $WATCH_NAMESPACE
subjects:
- kind: ServiceAccount
  name: pg-watcher
  namespace: $WATCH_NAMESPACE
roleRef:
  kind: Role
  name: pg-watcher-role
  apiGroup: rbac.authorization.k8s.io
